### ISSUE TITLE
AMP Validation error

### ISSUE THREAD

**Issue by ThierryA** [xwp/wp-travel-theme#77]
There seem to be an error with the search amp list array.

<img width="643" alt="screen shot 2018-05-03 at 11 14 23 am" src="https://user-images.githubusercontent.com/3581402/39568730-70050d90-4ec3-11e8-9e96-16579911d9a2.png">

You can see the error on the [home page](https://dev-amp-start-travel.pantheonsite.io/).

**Comment by DavidCramer** [comment]
@ThierryA I see the issue. The endpoint is not giving the right structure. Will sort it out.

**Comment by DavidCramer** [comment]
@postphotos This was a larger problem than just validation. In the ampstart theme ( https://ampstart-iframes.firebaseapp.com/templates/travel/travel.amp ) they tried to implement a predictive search on the search box. However, the template code in the demo is broken so it's not functioning. This broken code was implemented into Travel. 
I have corrected it now in #79 but it wont function yet since I'll need to implement a refresh to fetch new data. 
It will be nice to have this function, but we can talk about it in the sprint planning.
